//-----------------------------------------
//
// Generated by nedtool, version 3.3
// date: Thu Mar  6 23:54:18 2008
//
//-----------------------------------------


#include <math.h>
#include "omnetpp.h"

// NEDC version check
#define NEDC_VERSION 0x0303
#if (NEDC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedc: 'make clean' should help.
#endif

// Disable warnings about unused variables. For MSVC and BC only:
// GCC has no way to turn on its -Wunused option in a source file :(
#ifdef _MSC_VER
#  pragma warning(disable:4101)
#endif
#ifdef __BORLANDC__
#  pragma warn -waus
#  pragma warn -wuse
#endif

static cModuleType *_getModuleType(const char *modname)
{
    cModuleType *modtype = findModuleType(modname);
    if (!modtype)
        throw new cRuntimeError("Module type definition %s not found (Define_Module() missing from C++ code?)", modname);
    return modtype;
}

static void _checkModuleVectorSize(int vectorsize, const char *mod)
{
    if (vectorsize<0)
        throw new cRuntimeError("Negative module vector size %s[%d]", mod, vectorsize);
}

static void _readModuleParameters(cModule *mod)
{
    int n = mod->params();
    for (int k=0; k<n; k++)
        if (mod->par(k).isInput())
            mod->par(k).read();
}

static int _checkModuleIndex(int index, int vectorsize, const char *modname)
{
    if (index<0 || index>=vectorsize)
        throw new cRuntimeError("Submodule index %s[%d] out of range, sizeof(%s) is %d", modname, index, modname, vectorsize);
    return index;
}

static cGate *_checkGate(cModule *mod, const char *gatename)
{
    cGate *g = mod->gate(gatename);
    if (!g)
        throw new cRuntimeError("%s has no gate named %s",mod->fullPath().c_str(), gatename);
    return g;
}

static cGate *_checkGate(cModule *mod, const char *gatename, int gateindex)
{
    cGate *g = mod->gate(gatename, gateindex);
    if (!g)
        throw new cRuntimeError("%s has no gate %s[%d]",mod->fullPath().c_str(), gatename, gateindex);
    return g;
}

static cGate *_getFirstUnusedParentModGate(cModule *mod, const char *gatename)
{
    int baseId = mod->findGate(gatename);
    if (baseId<0)
        throw new cRuntimeError("%s has no %s[] gate",mod->fullPath().c_str(), gatename);
    int n = mod->gate(baseId)->size();
    for (int i=0; i<n; i++)
        if (!mod->gate(baseId+i)->isConnectedInside())
            return mod->gate(baseId+i);
    throw new cRuntimeError("%s[] gates are all connected, no gate left for `++' operator",mod->fullPath().c_str(), gatename);
}

static cGate *_getFirstUnusedSubmodGate(cModule *mod, const char *gatename)
{
    int baseId = mod->findGate(gatename);
    if (baseId<0)
        throw new cRuntimeError("%s has no %s[] gate",mod->fullPath().c_str(), gatename);
    int n = mod->gate(baseId)->size();
    for (int i=0; i<n; i++)
        if (!mod->gate(baseId+i)->isConnectedOutside())
            return mod->gate(baseId+i);
    int newBaseId = mod->setGateSize(gatename,n+1);
    return mod->gate(newBaseId+n);
}

static cFunctionType *_getFunction(const char *funcname, int argcount)
{
    cFunctionType *functype = findFunction(funcname,argcount);
    if (!functype)
        throw new cRuntimeError("Function %s with %d args not found", funcname, argcount);
    return functype;
}

static cChannel *_createChannel(const char *channeltypename)
{
    cChannelType *channeltype = findChannelType(channeltypename);
    if (!channeltype)
        throw new cRuntimeError("Channel type %s not found", channeltypename);
    cChannel *channel = channeltype->create("channel");
    return channel;
}

static cChannel *_createNonTypedBasicChannel(double delay, double error, double datarate)
{
    cBasicChannel *channel = new cBasicChannel("channel");
    if (delay!=0) channel->setDelay(delay);
    if (error!=0) channel->setError(error);
    if (datarate!=0) channel->setDatarate(datarate);
    return channel;
}

static cXMLElement *_getXMLDocument(const char *fname, const char *pathexpr=NULL)
{
    cXMLElement *node = ev.getXMLDocument(fname, pathexpr);
    if (!node)
        throw new cRuntimeError(!pathexpr ? "xmldoc(\"%s\"): element not found" : "xmldoc(\"%s\", \"%s\"): element not found",fname,pathexpr);
    return node;
}

ModuleInterface(Sim)
    // parameters:
    Parameter(playgroundSizeX, ParType_Numeric ParType_Const)
    Parameter(playgroundSizeY, ParType_Numeric ParType_Const)
    Parameter(numHosts, ParType_Numeric ParType_Const)
EndInterface

Register_ModuleInterface(Sim);

class Sim : public cCompoundModule
{
  public:
    Sim() : cCompoundModule() {}
  protected:
    virtual void doBuildInside();
};

Define_Module(Sim);

void Sim::doBuildInside()
{
    cModule *mod = this;

    // temporary variables:
    cPar tmpval;
    const char *modtypename;

    mod->setBackgroundDisplayString("p=0,0;b=$playgroundSizeX,$playgroundSizeY,rect;o=white");

    // submodules:
    cModuleType *modtype = NULL;
    int submodindex;

    //
    // submodule 'channelcontrol':
    //
    int channelcontrol_size = 1;
    modtype = _getModuleType("ChannelControl");
    cModule *channelcontrol_p = modtype->create("channelcontrol", mod);
    {
        cContextSwitcher __ctx(channelcontrol_p); // do the rest in this module's context

        // parameter assignments:
        channelcontrol_p->par("playgroundSizeX") = mod->par("playgroundSizeX");
        channelcontrol_p->par("playgroundSizeY") = mod->par("playgroundSizeY");

        _readModuleParameters(channelcontrol_p);
        channelcontrol_p->setDisplayString("p=50,25;i=eye14");
    }

    //
    // submodule 'host':
    //
    int host_size = (int)(mod->par("numHosts"));
    _checkModuleVectorSize(host_size,"host");
    cModule **host_p = new cModule *[host_size];
    if (host_size>0)
    {
        modtype = _getModuleType("Host");
    }
    for (submodindex=0; submodindex<host_size; submodindex++)
    {
        host_p[submodindex] = modtype->create("host", mod, host_size, submodindex);
        cContextSwitcher __ctx(host_p[submodindex]); // do the rest in this module's context

        _readModuleParameters(host_p[submodindex]);
        host_p[submodindex]->setDisplayString("p=50,50;i=node");
    }

    //
    // connections:
    //
    cGate *srcgate, *destgate;

    cChannel *channel;
    cPar *par;

    //
    // this level is done -- recursively build submodules too
    //
    channelcontrol_p->buildInside();
    for (submodindex=0; submodindex<host_size; submodindex++)
        host_p[submodindex]->buildInside();
    delete [] host_p;
}

class sim : public cNetworkType
{
  public:
    sim(const char *name) : cNetworkType(name) {}
    sim(const sim& n) : cNetworkType(n.name()) {operator=(n);}
    virtual void setupNetwork();
};

Define_Network(sim);

void sim::setupNetwork()
{
    // temporary variables:
    cPar tmpval;
    const char *modtypename;

    cModuleType *modtype;

    modtype = _getModuleType("Sim");
    cModule *sim_p = modtype->create("sim", NULL);

    cContextSwitcher __ctx(sim_p); // do the rest in this module's context
    // parameter assignments:
    sim_p->par("playgroundSizeX") = (tmpval=40, tmpval.setPrompt("playgroundSizeX"), tmpval.setInput(true), tmpval);
    sim_p->par("playgroundSizeY") = (tmpval=40, tmpval.setPrompt("playgroundSizeY"), tmpval.setInput(true), tmpval);
    sim_p->par("numHosts") = (tmpval=2, tmpval.setPrompt("Number of hosts:"), tmpval.setInput(true), tmpval);

    _readModuleParameters(sim_p);
    // build submodules recursively (if it has any):
    sim_p->buildInside();
}

